name: YouTube RSS Notifier

on:
  schedule:
    - cron: '0 * * * *' # 1時間に1回実行
  workflow_dispatch: # 手動実行用

jobs:
  check:
    runs-on: ubuntu-latest

    # Node.js 24への移行を明示する設定 2026/06/24以降は消してよい
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    permissions:
      contents: write # リポジトリへの書き込み権限が必要
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'

      - run: npm install

      - name: Run Script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: node check_videos.js

      - name: Commit and Push if ID updated
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add last_video_id.json
          git diff --cached --quiet || (git commit -m "Update last video ID" && git push)